"@inherits": base_config.yml
cluster:
  backend: ray
  ray:
    supervisor:
      standalone: no
      sub_pool_num: 0
session:
  custom_log_dir: null
storage:
  backends: [ray]
scheduling:
  autoscale:
    enabled: true
    scheduler_backlog_timeout: 10
